### ISSUE TITLE
Subsetting SFBM matrix

### ISSUE THREAD

**Issue by opain** [privefl/bigsparser#4]
Hello,

I am using LDpred2 to process multiple GWAS summary statistics. Currently LD matrices are subset to contain the SNPs within each GWAS, and then converted into the SFBM format. However, performing this process for each GWAS takes some time, and it might be faster to generate one SFBM matrix for all reference SNPs, and then subset the SFBM to contain the SNPs within each GWAS. 

Is it possible to subset an SFBM matrix?

Many thanks,

Ollie

**Comment by privefl** [comment]
First, to be sure, would you like to 
1. subset the SFBM and make another one smaller?
2. allow for operations on the SFBM as if you were using only a subset? (which is what I do in bigstatsr/bigsnpr)

The problem of 2. is that it is not straightforward to implement this for a sparse format.

For 1., I think if you precompute and store the LD matrices for each chromosome in the dsCMatrix format from the {Matrix} packages, those are easy to subset. And I think it would take a similar time subsetting those and making a new SFBM from the subsets (as I do in the paper) rather than directly subsetting the SFBM. Also note that recent updates to this package now allows the creation of the SFBM to be quite fast (e.g. I think it takes 10 minutes for HM3 variants) and is therefore fast compared to running LDpred2 (several hours).

**Comment by opain** [comment]
Thank you for your advice. Both scenarios 1 or 2 would have worked. Indeed, converting the dsCMatrix to SFBM only takes ~10mins and this is not a major issue. I just wanted to make sure I wasn't repeating this process unnecessarily. Many thanks.

**Comment by privefl** [comment]
If someone has some more straightforward idea how to simplify this, I'm open to suggestions :-)
